name: ai_builders_circle
description: AI Builders Circle Website
repository: https://github.com/fluttercommunity/ai_builders_circle
version: 1.0.0

environment:
  sdk: ^3.6.2

dependencies:
  jaspr: ^0.18.0
  jaspr_router: ^0.6.3
  web: ^1.1.0
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.1
  lints: ^5.1.1

jaspr:
  uses-ssr: false
